### ISSUE TITLE
missing string after doc export

### ISSUE THREAD

**Issue by renaudwangler** [MicrosoftLearning/10979-MicrosoftAzureFundamentals#20]
Hello.
On the second exercice, after exporting the document in Word format via the included powershell script the sting "E:\Labfiles\Mod04" in exercice 2, task2, [15] is changed to "E:04" probably due to the "\\" character in the string.

**Comment by polichtm** [comment]
apologies for a really late response - apparently I missed your remark. 
The issue has been corrected
rgds
Marcin
