### ISSUE TITLE
Problem with 10979D file

### ISSUE THREAD

**Issue by cgauthier95870** [MicrosoftLearning/10979-MicrosoftAzureFundamentals#24]
Hi
When we try to generate docx file with pandoc, we have error on file 10979Dxxx. It has a problem with MD file format, the message invalid-utf-8-stream-when-trying-to-convert-a-tex-fil appear.
I have testing, the problem is about the encoding file 10979Dxxx.
Anyone can corrected the problem or do we make the correction.
Cordially

**Comment by polichtm** [comment]
Can you identify the specific file you're having the problem with?
rgds
Marcin

**Comment by cgauthier95870** [comment]
Hi
File 10979d, not all, i don t remenber,
I test tomorrow morning, all lak file d and some lab files
Yesterday for test, i have copied word in file d on the file c version, and no problem
Cordially

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by pdlab** [comment]
Was there ever any resolution to this issue? Using the current pandoc script i cannot convert the files as the previous person commented on.

**Comment by polichtm** [comment]
We are looking into this. 
rgds
Marcin

**Comment by polichtm** [comment]
This has been resolved. Pls give it another try
rgds
Marcin

**Comment by cgauthier95870** [comment]
Thanks it's OK
Cédric
