### ISSUE TITLE
Error in Database Provider

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/10979-MicrosoftAzureFundamentals#42]
In Exercise 1 Task 1 it asks to use ClearDB, which no longer is an option.
Use MySql for Apps instead.
Then the Database options should be removed as well

Exercise 1: Creating and configuring a WordPress web app
Scenario
Your users have suggested that they would like to post blog articles to a corporate website. You have decided to host this website on Azure. In this exercise, you will create a website to host WordPress blogs and then test the website by posting articles to the site.

The main tasks for this exercise are as follows:

Create a web app
Install WordPress
Create a blog post
Task 1: Create a web app
From MIA-CL1, start Microsoft Edge, browse to http://portal.azure.com, and, when prompted, sign in by using the Microsoft account that is the Service Administrator of your Azure subscription.
From the Azure portal, create a new WordPress website based on the Azure Marketplace offering from WordPress, and then specify the following configuration:
App name: A unique name consisting of letters, digits, and hyphens

Subscription: Your Azure subscription

Resource Group: 10979D04-LabRG01

i.   App Service plan: **10979D04-SP1**.

ii.   Location: _The Azure region that is closest to your classroom location and that is available in your Azure subscription_

iii.   Pricing tier: **D1 Shared**
**Database Provider: ClearDB

Database

i.   Database Name: **10979d04_db1**

ii.   Database Type: **Shared**

iii.   Location: _The same location you chose for the App Service plan_

iv.   Pricing Tier: **Mercury**
Legal Terms (ClearDB): Purchase**

**Comment by polichtm** [comment]
updated
