### ISSUE TITLE
Instruction Problem

### ISSUE THREAD

**Issue by CentriqTraining** [MicrosoftLearning/10979-MicrosoftAzureFundamentals#43]
Many people take this course using an Azure pass:

Seems to me this didn't use to be the case, but some regions are **not AVAILABLE** in the Azure pass.
I remember when this first started, the Azure pass gave us very limited locations that certain items could be placed into, but after a short amount of time, that seemed to go away. Now it is back with a vengeance and is causing issues.

We encountered this in module 4 too and the time it would have take to correct it made it impossible to go back and fix.  If you follow the instructions, you will get to a point where what the instructions are asking you to do is impossible.  Now we are in Module 5...and we've hit it again.

In **module 5/Exercise 1/Task 1/Step 2**  - it has you create a virtual network....Under location, it says: "Azure data center closest to the location of your classroom" which would be Central US.

In **module 5/Exercise 1/Task 1/Step 3** - it has you create another virtual network...under location it says: "the same Azure region you chose when creating the first virtual network" which would be Central US

In **module 5/Exercise 2/Task 1/Step 1** - it has you create a VM...under location it says: "The same Azure region to which you deployed the two virtual networks in the first exercise of this lab"  which would be Central Us again, but you **CAN NOT** create a VM in Central US using Azure pass.  It tells you that the selected area is not available for this subscription.

The only way to fix is to delete you virtual networks, go back to the beginning and recreate - ignoring the instructions on location.  South Central works

**Comment by polichtm** [comment]
updated to account for restrictions applicable for offers such as Azure Pass. Btw. the region availability on per offer basis is documented at https://azure.microsoft.com/en-us/regions/offers/
rgds
Marcin
