### ISSUE TITLE
Incorrect VM name in 10979D_LAB_03.md

### ISSUE THREAD

**Issue by heas20180305** [MicrosoftLearning/10979-MicrosoftAzureFundamentals#45]
"Windows Server 2016 Datacenter Marketplace" is not available in Azure portal.
File: 10979D_LAB_03.md

**Comment by polichtm** [comment]
What images are you seeing? Is this related to you using an Azure Pass subscription? Pls refer to https://azure.microsoft.com/en-us/regions/offers/

**Comment by polichtm** [comment]
I assume this refers to the Azure Pass subscription. Let me know if this is not the case.
rgds
Marcin
