### ISSUE TITLE
10979D_LAB_03.md: Windows Server 2016 datacenter not available in all regions

### ISSUE THREAD

**Issue by heas20180305** [MicrosoftLearning/10979-MicrosoftAzureFundamentals#46]
Windows Server 2016 datacenter can not be created when region North Europe is selected.
Works if "West Europe" is selected

**Comment by polichtm** [comment]
That's expected if you are using Azure Pass. Pls refer to https://azure.microsoft.com/en-us/regions/offers/ 
rgds
Marcin

**Comment by heas20180305** [comment]
Correct, but helpful if it is stated in instructions
