### ISSUE TITLE
Lab Instructions using Azure Passes

### ISSUE THREAD

**Issue by CentriqTraining** [MicrosoftLearning/10979-MicrosoftAzureFundamentals#48]
Instructions starting in Module 3 for sure...(not sure if there are issues prior) instruct students to create a VM in a region that is not available to them when using the Azure 30 day Pass.

Can you please either a)  have the instructions use a universally acceptable region for US regardless of whether they use an azure pass or not, or  b)  give additional information regarding the appropriate region based on if they are using certain passes; or c) quit limiting Azure 30 day passes.

In labs where there are multiple steps that create resources in a given region, certain things (like vnet's and storage accounts) will work, but ultimately the students have to delete and redo because the VM can't be created in that region and can thus not use those already created resources.

Thought I already raised this issue and saw it fixed, but that could have been MS-20532C.

**Comment by polichtm** [comment]
Unfortunately there is no such region. It is up to the instructor to identify prior to the individual modules the region that students can use for labs.
rgds
Marcin
