### ISSUE TITLE
10979E not released yet

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/10979-MicrosoftAzureFundamentals#63]
To bad to see the E version as the default branch while the course is not released yet.
Confusing for students.

I know the D version is a separate branch, however it is not the default branch.

https://www.microsoft.com/en-au/learning/course.aspx?cid=10979E
In development
Publication date: 05 October 2018

Marcel

**Comment by polichtm** [comment]
Marcel, 
we're looking into this...
rgds
Marcin

**Comment by travellingtrainer** [comment]
Class is available as of 29/09
