### ISSUE TITLE
Module 6 OAuth Preview

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/10979-MicrosoftAzureFundamentals#70]
Exercise 2, task 2:
When uploading files to blob storage, you can choose between OAuth (in preview) and SAS. Uploading with the SAS option works fine, the OAuth option give an error.

Problem (in Xtremelabs): Edge selects the OAuth by default (and gives an error during upload). IE and Chrome select the SAS option by default (give no error).

![image](https://user-images.githubusercontent.com/10166617/48772361-75dd9080-ecc4-11e8-84b1-822db05e2647.png)

**Comment by polichtm** [comment]
updated
