### ISSUE TITLE
Exercise 2: Viewing billing, usage, and quotas data. Task 2 not correct

### ISSUE THREAD

**Issue by jorismathijssen** [MicrosoftLearning/10979-MicrosoftAzureFundamentals#71]
Currently following this course. The second task is not clear. 

First of all how do i navigate to the Azure Account Center.

Second, i cant seem to find the Overview -> billing history -> download usage page.
I cant make improvement because i don't know the correct page.

[10979E_LAB_01.md file with issues](https://github.com/MicrosoftLearning/10979-MicrosoftAzureFundamentals/blob/master/Instructions/10979E_LAB_01.md)

**Comment by renaudwangler** [comment]
Hi !
You should direct your students to use the LAK (Lab Answer Keys) for detailed steps in the labs' walkthrough.

**Comment by polichtm** [comment]
That's correct - pls use LAK and let us know if this does not suffice
thnx
Marcin
