### ISSUE TITLE
Module 7 Lab instructions do not work

### ISSUE THREAD

**Issue by NicoThiemer** [MicrosoftLearning/10979-MicrosoftAzureFundamentals#77]
The command in lab 7 instructions in Task 2, step 2 do not work, because the quickstart template was changed from user/password to ssh! Please fix this asap.

**Comment by polichtm** [comment]
updated

**Comment by XtremeDR** [comment]
Looks like the Lab Steps doc was updated here but not the LAK, it still has the old instructions that fail. Could we ask you to update the LAK as well?

**Comment by polichtm** [comment]
updated
